# Generated by Django 4.2.6 on 2024-01-03 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='proprietaire',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compte', to='app.utilisateur'),
        ),
    ]
