# Generated by Django 4.2.6 on 2024-01-03 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_compte_proprietaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='destinateur_nom',
            new_name='destinataire_nom',
        ),
    ]
