# Generated by Django 4.2.6 on 2024-01-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_utilisateur_numero_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(default='adamaholivia444@gmail.com', max_length=254),
        ),
    ]
